### ISSUE TITLE
_tkinter.TclError: invalid command name ".!entry"

### ISSUE THREAD

**Issue by kettle-7** [Kettle3D/Kettle3D#2]
I get this error when I leave the options menu. The full traceback looks like this:  
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Kettle\AppData\Roaming\Panda3D\Panda3D-1.10.6-x64\python\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Kettle\AppData\Roaming\Kettle3D\kettle3DLauncher.py", line 989, in unoptions
    unoptions2()
  File "C:\Users\Kettle\AppData\Roaming\Kettle3D\kettle3DLauncher.py", line 949, in unoptions2
    if world_entry.get() is not None and world_entry.get() != '':
  File "C:\Users\Kettle\AppData\Roaming\Panda3D\Panda3D-1.10.6-x64\python\lib\tkinter\__init__.py", line 2682, in get
    return self.tk.call(self._w, 'get')
_tkinter.TclError: invalid command name ".!entry"`
Does anyone know what's going on? I'm going to try investigating it further.

**Comment by kettle-7** [comment]
I fixed it with the use of a StringVar object
